# Generated by Django 5.1.1 on 2024-10-25 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='response',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='runner.runnerresponse'),
            preserve_default=False,
        ),
    ]
