# Generated by Django 5.1.1 on 2024-10-21 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pae', '0001_initial'),
        ('scheduler', '0002_serviceaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paedestination',
            name='report_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddConstraint(
            model_name='paedestination',
            constraint=models.UniqueConstraint(fields=('email', 'service', 'report_id'), name='unique_email_service_report_combination'),
        ),
    ]
