# Generated by Django 5.1.1 on 2024-10-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pae', '0002_paedestination_report_id_and_more'),
        ('scheduler', '0003_alter_serviceaction_request_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paedestination',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddIndex(
            model_name='paedestination',
            index=models.Index(fields=['service', 'report_id', 'is_active'], name='pae_paedest_service_20f4fe_idx'),
        ),
    ]
