# Generated by Django 5.1.1 on 2024-10-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pae', '0003_alter_paedestination_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paedestination',
            name='report_id',
            field=models.IntegerField(default=0),
        ),
    ]
