# Generated by Django 5.1.1 on 2024-10-26 14:17

import django.utils.timezone
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pae', '0004_alter_paedestination_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paedestination',
            name='cron_update_interval',
            field=models.CharField(blank=True, default='* * * * *', help_text="Here you can specify an interval for updates, following the use of Cron expressions, valid examples are '* 12 * * ?', ", max_length=100, null=True, validators=[utils.validators.validate_crontab]),
        ),
        migrations.AddField(
            model_name='paedestination',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='paedestination',
            name='report_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
