# Generated by Django 5.1.1 on 2024-10-09 19:54

import dispatcher.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=200, validators=[dispatcher.models.validate_email_or_url])),
                ('last_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('cron_update_interval', models.CharField(blank=True, default='* * * * *', help_text="Here you can specify an interval for updates, following the use of Cron expressions, valid examples are '* 12 * * ?', ", max_length=100, null=True, validators=[dispatcher.models.validate_crontab])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
