# Generated by Django 5.1.1 on 2024-10-17 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(help_text='Name of the method (e.g., reportStudentLackPerformance)', max_length=255)),
                ('description', models.TextField(help_text='Description of the service action')),
                ('request_template', models.JSONField(default={'BACOSESS': '{{BACOSESS}}', 'data': {'checkOnlyMode': False, 'methodName': 'pedgogicReport', 'serviceArguments': [{'name': 'importYear', 'position': 0, 'type': 'String', 'value': '{{importYear}}'}]}, 'serviceJson': 'WSPeriodicApiFacade'}, help_text='Template of the request body for this action')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='scheduler.service')),
            ],
        ),
    ]
