# Generated by Django 5.1.1 on 2024-10-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_serviceaction_request_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='delivery_endpoint',
            field=models.CharField(blank=True, help_text="Optional: Should be set for 'On Request' delivery type. Provides a callable internal endpoint. Ex.: 'https://www.(domain).com/services/api/(delivery_endpoint)/", max_length=40, null=True, unique=True),
        ),
    ]
