# Generated by Django 5.1.1 on 2024-10-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('info', 'Info'), ('error', 'Error')], max_length=7)),
                ('log_level', models.CharField(choices=[('1', 'Minimal'), ('2', 'Below Average'), ('3', 'Average'), ('4', 'Major'), ('5', 'Verbose')], max_length=15)),
            ],
        ),
    ]
